### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by Ultra119**
plz don't delete all lines in the next update🥺

### CODE REVIEW

**Comment by EBTX11** [comment]
I'm sorry I had no choice but now that the translations are synthesized in a single folder this will allow you to update the translation instead of redoing everything each time. I will implement it in the next update

**Comment by Ultra119** [comment]
updated to include the changes in 3.6.*.

**Comment by Ultra119** [comment]
Sorry, that's not all. I'll update the translation when strings of new concepts are added to the original.

**Comment by Ultra119** [comment]
3.6.5. sorry for force-push, but there is no other way, because you are not merging pull request.

**Pull request merged**
